# location where article database will be stored
data_dir: "~/.lit"

# location where article markdown notes will be stored
notes_dir: "~/notes"

# development mode options
dev_mode: false
dev_mode_subsample: 500
