# location where article database will be stored
data_dir: "~/.lit"

# location where article markdown notes will be stored
notes_dir: "~/notes"

# development mode
dev_mode:
  enabled: false
  subsample: 500
